import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { PropsWithChildren } from 'react';

import { Hero, Title } from '@/components/atoms';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <head>
        <meta name="darkreader-lock" />
      </head>
      <body className={inter.className}>
        <Hero>
          <main className="flex flex-col items-center justify-between">
            <Title>My dev friends</Title>
            {children}
          </main>
        </Hero>
      </body>
    </html>
  );
}
